# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller:
        enabled:              '%kernel.debug%'
        profiler:             false
#    read_from:            '%assetic.read_from%'
    write_to:             '%kernel.root_dir%/../web'
    java: /usr/bin/java
    node: /usr/bin/node
    node_paths:
        - "%kernel.root_dir%/../node_modules"  
        - /usr/lib/node_modules
        - /usr/lib/nodejs
        - /usr/share/javascript
    ruby: /usr/bin/ruby
    filters:
#        autoprefixer: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        coffee: ~
        compass:
            bin: /usr/local/bin/compass
        csscachebusting: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.4.5.jar"
        cssimport: ~
        cssmin: ~
        cssrewrite: ~
        dart:
            bin: /usr/lib/dart/bin/dart2js
        emberprecompile:
            bin: /usr/bin/ember
        gss:
            jar: "%kernel.root_dir%/Resources/java/closure-stylesheets-library.jar"
        handlebars: ~
        jpegoptim: ~
        jpegtran: ~
        jsmin: ~
        jsminplus: ~
        jsqueeze: ~
        less:
            bin: "%kernel.root_dir%/../node_modules/.bin/lessc"
        minifycsscompressor: ~
        optipng: ~
        packager: ~
        packer: ~
        phpcssembed: ~
        pngout:
            bin: "%kernel.root_dir%/../node_modules/.bin/pngout"
#            bin: "%kernel.root_dir%/../bin/pngout"
        reactjsx:
            bin: /usr/bin/jsx
        roole: ~
        sass:
            bin: "%kernel.root_dir%/../node_modules/.bin/node-sass"
#            bin: /usr/local/bin/sass
        scss: ~
        sprockets:
            lib: /usr/local/bin/sprockets
        typescript: ~
        uglifycss:
            # on utilise le uglifycss installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifycss"
        uglifyjs2:
            # on utilise le uglifyjs installé localement
            bin: "%kernel.root_dir%/../node_modules/.bin/uglifyjs"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
    bundles:
        - IlcfranceOrangetoolsResBundle
        - IlcfranceOrangetoolsSecurityBundle
        - IlcfranceOrangetoolsFrontBundle
        - IlcfranceOrangetoolsAdminBundle

    assets:

        # afarkas html5shiv
        html5shiv:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/html5shiv/dist/html5shiv-printshiv.min.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/html5shiv/min.js'

        # scottjehl respond
        respond:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/respond/dest/respond.src.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/respond/min.js'

        # html5shiv.respond.min.js
        html5shiv_respond_min_js:
            inputs:
                - '@html5shiv'
                - '@respond'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/html5shiv.respond.min.js'

        # Jquery
        jquery1:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery1/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/v1.min.js'

        # Jquery
        jquery2:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery2/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/v2.min.js'

        # Jquery
        jquery3:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery3/dist/jquery.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/v3.min.js'

        # jquery nicescroll
        jquery_nicescroll:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery.nicescroll/jquery.nicescroll.min.js'
            combine: true
            output: 'js/jquery/nicescroll/min.js'

        jquery_nicescroll_img:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery.nicescroll/zoomico.png'
            output: 'js/jquery/nicescroll/zoomico.png'

        jquery_nicescroll_img2:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery.nicescroll/zoomico.png'
            output: 'js/zoomico.png'

        # jquery-slimscroll
        jquery_slimscroll:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery-slimscroll/jquery.slimscroll.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/slimscroll/min.js'

        # jquery-fastclick
        jquery_fastclick:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/fastclick/lib/fastclick.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/fastclick/min.js'

        # bootstrap_min_js
        bootstrap_min_js:
            inputs:
                - "%kernel.root_dir%/../web/res/bower_components/bootstrap3/dist/js/bootstrap.js"
            filters:
                - uglifyjs2
            combine: true
            output: 'js/bootstrap/min.js'

        # error.min.js
        error_min_js:
            inputs:
                - '@jquery_nicescroll'
                - '@jquery_slimscroll'
                - '@jquery_fastclick'
                - '@bootstrap_min_js'
                - '%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/js/base.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/error.min.js'

        # hacker_bootstrap_less
        hacker_bootstrap_less:
            inputs: "%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/less/hacker-bootstrap/hacker.less"
            filters:
                - less
                - cssrewrite
            output: 'css/hacker-bootstrap.css'

        # ilcfrance_orangetools_theme_less
        ilcfrance_orangetools_theme_less:
            inputs: "%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/less/sasedev/sasedev.less"
            filters:
                - less
                - cssrewrite
            output: 'css/theme.css'

        # frameworkerror.min.css
        ilcfrance_orangetools_frameworkerror_min_css:
            inputs:
#                - '%kernel.root_dir%/../web/bundles/framework/css/structure.css'
#                - '%kernel.root_dir%/../web/bundles/framework/css/body.css'
#                - '%kernel.root_dir%/../web/bundles/framework/css/exception.css'
                - '@hacker_bootstrap_less'
                - '@ilcfrance_orangetools_theme_less'
                - "%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/css/error.css"
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'css/frameworkerror.min.css'

        # mnot hinclude
        hinclude:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/hinclude/hinclude.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/hinclude/min.js'

        # jquery1.hinclude.min.js
        jquery1_hinclude_min_js:
            inputs:
                - '@jquery1'
                - '@hinclude'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery1.hinclude.min.js'

        # jquery2.hinclude.min.js
        jquery2_hinclude_min_js:
            inputs:
                - '@jquery2'
                - '@hinclude'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery2.hinclude.min.js'

        # jquery3.hinclude.min.js
        jquery3_hinclude_min_js:
            inputs:
                - '@jquery3'
                - '@hinclude'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery3.hinclude.min.js'

        # moment
        moment_min_js:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/moment/min/moment-with-locales.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/moment/with-locales.min.js'

        # moment-timezone
        moment_timezone_min_js:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/moment-timezone/builds/moment-timezone-with-data-2012-2022.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/moment/timezone-with-data-2012-2022.js'

        # jquery.easing.js
        jquery_easing_min_js:
            inputs:
                - '%kernel.root_dir%/../web/res/bower_components/jquery.easing/js/jquery.easing.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/easing/min.js'

        # jquery.form.js
        jquery_form_min_js:
            inputs:
                 - '%kernel.root_dir%/../web/res/bower_components/jquery-form/src/jquery.form.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/jquery/form/min.js'



        # FontAwesome
        # temps
        # final output
        font_awesome_less:
            inputs: "%kernel.root_dir%/../web/res/bower_components/font-awesome/less/font-awesome.less"
            filters:
                - less
                - cssrewrite
            output: 'css/font-awesome.css'

        # Ionicons
        # temps
        # final output
        ionicons_less:
            inputs: "%kernel.root_dir%/../web/res/bower_components/ionicons/less/ionicons.less"
            filters:
                - less
                - cssrewrite
            output: 'css/ionicons.css'

        # bootstrap
        # final output
        bootstrap_less:
            inputs: "%kernel.root_dir%/../web/res/bower_components/bootstrap3/less/bootstrap.less"
            filters:
                - less
                - cssrewrite
            output: 'css/bootstrap.css'

        ilcfrance_orangetools_skin_all_less:
            inputs: "%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/less/sasedev/skins/_all-skins.less"
            filters:
                - less
                - cssrewrite
            output: 'css/skins.css'

        tinymce_min_js:
            inputs:
                 - '%kernel.root_dir%/../web/res/bower_components/tinymce/jquery.tinymce.min.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/tinymce-dist/min.js'

        select2_scss:
            inputs: "%kernel.root_dir%/../web/res/bower_components/select2/src/scss/core.scss"
            filters:
                - scss
                - cssrewrite
            output: 'css/select2.css'

        select2_min_js:
            inputs:
                 - '%kernel.root_dir%/../web/res/bower_components/select2/dist/js/select2.full.js'
                 - '%kernel.root_dir%/../web/res/bower_components/select2/dist/js/i18n/*.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/select2/min.js'
            

        # fulltemplate.min.css
        ilcfrance_orangetools_fulltemplate_min_css:
            inputs:
                - '@font_awesome_less'
                - '@ionicons_less'
                - '@bootstrap_less'
                - '@select2_scss'
                - '@ilcfrance_orangetools_theme_less'
                - '@ilcfrance_orangetools_skin_all_less'
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net-bs/css/dataTables.bootstrap.css'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-modal/css/bootstrap-modal-bs3patch.css'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-modal/css/bootstrap-modal.css'
                - '%kernel.root_dir%/../web/res/bower_components/smalot-bootstrap-datetimepicker/css/bootstrap-datetimepicker.css'
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/css/fileinput.css'
                - '%kernel.root_dir%/../web/res/bower_components/iCheck/skins/minimal/minimal.css'
            filters:
                - cssrewrite
                - minifycsscompressor
                - yui_css
            combine: true
            output: 'css/fulltemplate.min.css'

        # app.min.js
        app_min_js:
            inputs:
                - '@jquery_nicescroll'
                - '@jquery_slimscroll'
                - '@jquery_fastclick'
                - '@bootstrap_min_js'
                - '%kernel.root_dir%/../src/Ilcfrance/Orangetools/ResBundle/Resources/js/base.js'
                - '@moment_min_js'
                - '@moment_timezone_min_js'
                - '%kernel.root_dir%/../web/res/bower_components/iCheck/icheck.js'
                - '@tinymce_min_js'
                - '@select2_min_js'
                - '%kernel.root_dir%/../web/res/bower_components/datatables.net/js/jquery.dataTables.js'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-modal/js/bootstrap-modalmanager.js'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-modal/js/bootstrap-modalmanager.js'
#                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-modal/js/bootstrap-modal.js'
                - '%kernel.root_dir%/../web/res/bower_components/smalot-bootstrap-datetimepicker/js/bootstrap-datetimepicker.js'
                - '%kernel.root_dir%/../web/res/bower_components/smalot-bootstrap-datetimepicker/js/locales/*.js'
                - '%kernel.root_dir%/../web/res/bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.js'
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/js/fileinput.js'
                - '%kernel.root_dir%/../web/res/bower_components/bootstrap-fileinput/js/fileinput_locale_*.js'
            filters:
                - uglifyjs2
            combine: true
            output: 'js/app.min.js'

